### ISSUE TITLE
Failure context should be provided in the test file, not inside the library

### ISSUE THREAD

**Issue by b33j0r** [b33j0r/climactic#4]
Currently, the test output does not show where in the input a problem occurred.

```
.F..
======================================================================
FAIL: test_hello_failure.yml
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brjorgensen/PycharmProjects/climactic/climactic/case.py", line 96, in runTest
    command.run(None, self)
  File "/Users/brjorgensen/PycharmProjects/climactic/climactic/commands.py", line 188, in run
    actual.strip()
AssertionError: 'Hello world!' != 'Um, hi!'
- Hello world!
+ Um, hi!


----------------------------------------------------------------------
Ran 4 tests in 0.023s

FAILED (failures=1)
```

Unfortunately, I think giving context in the YAML files will require extending PyYAML. Open to an easier solution, but I would like to see something like this:

```
.F..
======================================================================
FAIL: test_hello_failure.yml
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/brjorgensen/PycharmProjects/climactic/climactic/case.py", line 96, in runTest
    command.run(None, self)
  File "/Users/brjorgensen/PycharmProjects/climactic/examples/test_hello_failure.yml", line 7, in assert-output
    - assert-output: >
       Hello world!

AssertionError: 'Hello world!' != 'Um, hi!'
- Hello world!
+ Um, hi!


----------------------------------------------------------------------
Ran 4 tests in 0.023s

FAILED (failures=1)
```

**Comment by b33j0r** [comment]
https://gist.github.com/dagss/5008118

Not exactly what climactic needs, but a good start to keep in mind.
